### ISSUE TITLE
Prevent sorting of only *some* columns?

### ISSUE THREAD

**Issue by adamrp** [jairideout/Keemei#36]
Not sure what the Google Sheets add-ons API permits, but @rob-knight pointed out that a frequent problem is that people sometimes sort the rows of their mapping files but accidentally do not select all the columns (resulting in "scrambled" metadata files)

**Comment by jairideout** [comment]
That'd be really useful but unfortunately an add-on can't alter the sorting functionality provided by Google Sheets (see the description [here](https://developers.google.com/apps-script/add-ons/) under the heading "But keep the restrictions in mind" for details).

**Comment by adamrp** [comment]
Ok thanks for checking anyways!
